export const BOOKING_LICENSE_STATUS = {
  NOT_STARTED: "NOT_STARTED",
  STARTED: "STARTED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};

export const BOOKING_LICENSE_STATUS_TO_STATUS: any = {
  NOT_STARTED: "Not Checked In",
  STARTED: "Checked In",
  COMPLETED: "Checked Out",
  CANCELLED: "Cancelled",
};

export const PRODUCT_TYPES = {
  ROOM: "ROOM",
  ADDON: "ADDON",
  EXPENSE: "EXPENSE",
};

export const BOOKING_STATUS = {
  OPEN: "OPEN",
  CLOSED: "CLOSED",
};

export const BOOKING_SOURCE_TAGS = {
  WALK_IN: "WALK_IN",
  PHONE_EMAIL: "PHONE_EMAIL",
  OTA: "OTA",
  TRAVEL_AGENT: "TRAVEL_AGENT",
  CORPORATE: "CORPORATE",
  MICE: "MICE",
  CHARTER: "CHARTER",
};

export const BOOKING_PAYTYPE = {
  DIRECT: "DIRECT",
  BILL_TO_COMPANY: "BILL_TO_COMPANY",
  ADHOC: "ADHOC",
  PARTIAL: "PARTIAL",
};
