export const PAY_TYPES = {
  CASH: "CASH",
  CREDIT_CARD: "CREDIT_CARD",
  NET_BANKING: "NET_BANKING",
  UPI: "UPI",
  BANK_TRANSFER: "BANK_TRANSFER",
  AMEX: "AMEX",
  ONLINE: "ONLINE",
  CHEQUE: "CHEQUE",
};
